---
# file: roles/postgresql_server/tasks/main.yml

- name: Make sure PostgreSQL repository is included
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main'
  tags:
      - postgres

- name: Make sure the PostgreSQL key is present
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc
  tags:
      - postgres

- name: Make sure the necessary packages are installed for PostgreSQL (common from raring repo)
  apt: name={{ item }} default_release=raring update-cache=true
  with_items:
    - postgresql-common

- name: Make sure the necessary packages are installed for PostgreSQL
  apt: name={{ item }}
  with_items:
    - postgresql-9.1
    - postgresql-contrib-9.1
    - python-psycopg2
    - libpostgresql-jdbc-java
  tags:
    - postgres