---
# file: roles/cdh_hbase-master/tasks/main.yml

- name: Make sure rsyslog is setup for hbase-master
  template: src=rsyslog.conf dest=/etc/rsyslog.d/60-hbase-master.conf owner=root group=root mode=0644
  tags: rsyslog
  notify:
    - restart rsyslog

- name: Make sure the hbase-master service is installed
  apt: name=hbase-master
  tags: hbase
  notify:
    - start hbase-master