---
# file: roles/cdh_hive_config/tasks/main.yml

- name: Copy /etc/hive/conf.empty to /etc/hive/conf.{{ site_name }}
  shell: creates=/etc/hive/conf.{{ site_name }} cp -R -p /etc/hive/conf.dist /etc/hive/conf.{{ site_name }}
  tags: hive

- name: Make sure Hive has the correct configuration in /etc/hive/conf.{{ site_name }}
  template: src={{ item }} dest=/etc/hive/conf.{{ site_name }}/{{ item }} owner=root group=root mode=0644
  with_items:
    - hive-site.xml
  notify:
    - restart hive-metastore
  tags:
    - hive
    - configuration

- name: Ubuntu 'update-alternatives' install Hive configuration
  shell: update-alternatives --install /etc/hive/conf hive-conf /etc/hive/conf.{{ site_name }} 50
  tags: hive

- name: Ubuntu 'update-alternatives' set Hive configuration
  shell: update-alternatives --set hive-conf /etc/hive/conf.{{ site_name }}
  tags: hive

- shell:  ln -s /usr/share/java/postgresql-jdbc4.jar /usr/lib/hive/lib/postgresql-jdbc4.jar
  tags: hive