---
# file: roles/presto_worker/tasks/main.yml

- name: Make sure Presto worker is configured
  template: src={{ item }} dest=/usr/local/presto/etc/{{ item }} owner=root group=root mode=0644
  with_items:
    - config.properties
  tags: presto