---
# file: roles/aggregated_links_common/tasks/main.yml
# see https://help.ubuntu.com/community/UbuntuBonding

- name: Make sure ifenslave-2.6 is installed
  apt: pkg=ifenslave-2.6
  tags: bonding

- name: Make sure the bonding kernel module is loaded
  lineinfile: dest=/etc/modules regexp="bonding" line=bonding
  tags: bonding