---
# file: roles/td_agent/tasks/main.yml

- name: Make sure the Treasure Data repository is available
  apt_repository: repo='deb http://packages.treasure-data.com/precise/ precise contrib'
  tags: tdagent

- name: Make sure td-agent is installed
  apt: pkg=td-agent update_cache=yes force=yes
  tags: tdagent

- name: Make sure the fluent elasticsearch plugin is installed
  shell: creates=/usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-elasticsearch-0.1.2/Gemfile /usr/lib/fluent/ruby/bin/fluent-gem install fluent-plugin-elasticsearch
  tags: tdagent

- template: src=td-agent.conf dest=/etc/td-agent/td-agent.conf owner=root group=root mode=0644
  tags: tdagent
  notify:
    - restart td-agent