---
# file: roles/cdh_hadoop_datanode/tasks/main.yml

- name: Make sure the /data/dfs/dn directory exists
  file: path=/data/dfs/dn owner=hdfs group=hdfs state=directory
  tags: hadoop

- name: Make sure hadoop-hdfs-datanode service is installed
  apt: name=hadoop-hdfs-datanode
  tags: hadoop

- name: Make sure rsyslog is setup for hadoop-hdfs-datanode
  template: src=rsyslog.conf dest=/etc/rsyslog.d/60-hadoop-hdfs-datanode.conf owner=root group=root mode=0644
  tags: rsyslog
  notify:
    - restart rsyslog